/**
 * Builds a readable report model from decoded Crystal Reports streams.
 *
 * The record layouts used here were identified by analysing decrypted sample reports. Only
 * information whose position is well established is extracted; everything else stays available
 * in the lossless record tree. This model is informational and is never used to write .rpt files.
 */

import type { RecordNode, RecordPart } from './records.ts';
import { stringAt, stringsIn, tokenize } from './strings.ts';

// Report definition (Contents) record types
const REPORT_ROOT = 0x0064;
const NAMED_VALUE = 0x0071;
const FORMULA = 0x0076;
const FORMULA_WRAPPER = 0x0077;
const PARAMETER = 0x007a;
const SUMMARY = 0x007e;
const SQL_EXPRESSION = 0x0081;
const SORT_FIELD = 0x0029;
const GROUP = 0x00e5;
const AREA = 0x008a;
const SECTION = 0x008c;
const OBJECT_NAME = 0x009e;
const OBJECT_POSITION = 0x00be;
// Text objects hold paragraphs (0x00c0 ... 0x00c1) of text runs (0x00c2) and embedded fields (0x00c4).
const TEXT_PARAGRAPH = 0x00c0;
const TEXT_CONTENT = 0x00c2;
const TEXT_EMBEDDED_FIELD = 0x00c4;
const FONT = 0x0008;
const FONT_COLOR = 0x0100;
const BORDER = 0x00ec;
const SAVE_INFO = 0x0178;
const PRINTER_MODE = 0x0007;
const PAGE_SETUP = 0x0066;
const RUNNING_TOTAL = 0x0080;
const OLE_ITEM = 0x00bd;

// Formatting-condition wrappers: their own bytes are slots of (formula name, flag, formula index).
const SECTION_CONDITIONS = 0x00ff;
const SECTION_FORMAT = 0x00fe;
const FONT_CONDITIONS = 0x0101;

// Chart records that follow a chart object.
const CHART_LAYOUT = 0x011c;
const CHART_VALUES = 0x011f;
const CHART_TITLES = 0x0121;
const CHART_FIELD = 0x0126;
const CHART_ON_CHANGE_OF = 0x0119;

// Cross-tab block: start/end markers, column and row dimensions, cells.
const CROSSTAB_START = 0x00b9;
const CROSSTAB_END = 0x00ba;
const CROSSTAB_COLUMN = 0x00cc;
const CROSSTAB_ROW = 0x00cd;
const CROSSTAB_DIMENSION = 0x00cb;

const OBJECT_KINDS: Record<number, string> = {
  0x009f: 'field',
  0x00a5: 'text',
  0x00a9: 'lineOrBox',
  0x00ae: 'graphic',
  0x00a3: 'subreport',
  0x00b8: 'crossTab',
};

/** Top-level wrappers that introduce an object, and the kind they create. */
const OBJECT_WRAPPERS: Record<number, string> = {
  0x00aa: 'line',
  0x00ac: 'box',
  0x00af: 'picture',
  0x00b4: 'chart',
};

// Query engine (QESession) record types
const QE_CONNECTION = 0x0002;
const QE_TABLE = 0x0003;
const QE_FIELD = 0x0004;
const QE_LINK = 0x000a;
const QE_CONNECTION_PROPERTY = 0x0009;

/** Field value types as stored in the query engine and on named values. */
const VALUE_TYPES: Record<number, string> = {
  12: 'memo',
  // 0-5: signed/unsigned 8, 16 and 32-bit integers.
  0: 'integer',
  1: 'integer',
  2: 'integer',
  3: 'integer',
  4: 'integer',
  5: 'integer',
  6: 'number',
  7: 'currency',
  8: 'boolean',
  9: 'date',
  10: 'time',
  11: 'string',
  13: 'memo',
  14: 'blob',
  15: 'dateTime',
  // Bitmap, icon, picture, OLE object and chart fields.
  16: 'blob',
  17: 'blob',
  18: 'blob',
  19: 'blob',
  20: 'blob',
};

/** Summary operations by the first byte of a summary record (Crystal's summary operation numbers). */
const SUMMARY_OPERATIONS: Record<number, string> = {
  0: 'sum', 1: 'average', 2: 'variance', 3: 'standard deviation', 4: 'maximum', 5: 'minimum', 6: 'count',
  7: 'pop. variance', 8: 'pop. standard deviation', 9: 'distinct count', 13: 'median', 17: 'mode',
};
/** A summary in a chart: "Sum of {field}" etc. */
const SUMMARY_WRAPPER = 0x007f;

const SELECTION_FORMULAS: Record<string, keyof SelectionFormulas> = {
  'Record Selection': 'record',
  'Group Selection': 'group',
  'Saved Data Selection': 'savedData',
  Record_Selection: 'record',
  Group_Selection: 'group',
  Saved_Data_Selection: 'savedData',
};

export interface FormulaInfo {
  name: string;
  /** Position in the report's formula list (0-based); formatting conditions refer to formulas by it. */
  index?: number;
  /** "formula" (user formula), "conditionalFormat" (formatting condition) or "internal" (generated by Crystal). */
  kind?: 'formula' | 'conditionalFormat' | 'internal';
  text: string;
  referencedFields: string[];
  /** The formula's result type, as Crystal stores it (number, currency, string, date, ...). */
  valueType?: string;
}

export interface SelectionFormulas {
  record?: string;
  group?: string;
  savedData?: string;
}

/** Reference to a formula: its name and its position in the report's formula list (0-based). */
export interface FormulaRef {
  name: string;
  index: number;
}

export interface TextStyle {
  /** Point size. */
  size?: number;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  /** "#RRGGBB" */
  color?: string;
}

export interface BorderInfo {
  /** Border line style per side (0 = none, 1 = single, ...): left, right, top, bottom. */
  sides: [number, number, number, number];
  color?: string;
  /** Fill colour ("#RRGGBB"); absent when transparent. */
  background?: string;
  /** Line width in twips. */
  width?: number;
}

export interface CrossTabInfo {
  rows: string[];
  columns: string[];
  summaries: string[];
}

export interface ChartInfo {
  /** Summarised values shown by the chart, e.g. "Sum of Orders.Order Amount". */
  values: string[];
  /** Field the chart is drawn "on change of", when stored. */
  onChangeOf?: string;
  title?: string;
  categoryTitle?: string;
  valueTitle?: string;
  /** Chart layout: 0 advanced ("on change of" fields of its own), 1 group, 2 cross-tab. */
  layoutCode?: number;
  /** Raw chart style code: the family byte and the graph type byte together. */
  styleCode?: number;
  /** Chart family, in the order of Crystal's Chart Expert (0 bar, 1 line, 2 area, 3 pie, 4 doughnut, ...). */
  family?: number;
  /** Crystal graph type (CrGraphType: 0 side-by-side bar, 1 stacked bar, 30 pie, 31 3D pie, 40 doughnut, ...). */
  graphType?: number;
  /** A second "on change of" field: one series per value of it (several lines or bar colours). */
  series?: string;
  /** How the categories and the series are ordered: 0 ascending, 1 descending, 2 as the data comes (original order). */
  categoryOrder?: number;
  seriesOrder?: number;
  /** Whether the legend shows, and where (0 right, 1 left, 2 bottom, 3 top). */
  legend?: { visible: boolean; position: number };
  /** What each data point is labelled with (0 nothing, 1 its category, 2 its value, 3 both) and the label's number format (Chart Expert list index). */
  dataLabels?: { kind: number; format: number };
}

/** A number format of a field (Crystal's Format Editor, Number tab). */
export interface NumberFormatInfo {
  decimals: number;
  thousands: boolean;
  leadingZero: boolean;
  /** 0 none, 1 leading minus, 2 trailing minus, 3 brackets. */
  negative: number;
  /** 0 no symbol, 1 fixed, 2 floating. */
  symbolType: number;
  symbol: string;
  /** 0 leading inside the negative sign, 1 leading outside, 2 trailing inside, 3 trailing outside. */
  symbolPosition: number;
}

/** A date format (Date tab). */
export interface DateFormatInfo {
  /** 0 year-month-day, 1 day-month-year, 2 month-day-year. */
  order: number;
  /** 0 short (yy), 1 long (yyyy), 2 none. */
  year: number;
  /** 0 numeric, 1 leading zero, 2 short name, 3 long name, 4 none. */
  month: number;
  /** 0 numeric, 1 leading zero, 2 none. */
  day: number;
  /** 0 short name, 1 long name, 2 none. */
  dayOfWeek: number;
  /** Separators between the first and second, and the second and third parts. */
  separators: [string, string];
}

/** A time format (Time tab). */
export interface TimeFormatInfo {
  hour12: boolean;
  seconds: boolean;
  am: string;
  pm: string;
  hourMinute: string;
  minuteSecond: string;
}

/** How a field shows its value: the number format for currency values and for other numbers, date and time. */
export interface ValueFormat {
  /** The field keeps Crystal's default format (not customised in the Format Editor). */
  systemDefault?: boolean;
  currency?: NumberFormatInfo;
  number?: NumberFormatInfo;
  date?: DateFormatInfo;
  time?: TimeFormatInfo;
  /** 0 date then time, 1 time then date, 2 date only, 3 time only. */
  dateTimeOrder?: number;
  dateTimeSeparator?: string;
}

export interface ReportObject {
  kind: string;
  name: string;
  /** Horizontal alignment set on the object (absent: Crystal's default for the value type). */
  align?: 'left' | 'center' | 'right' | 'justify';
  /** Suppressed (the Suppress box ticked): not shown, though a formula in it still runs. */
  suppressed?: boolean;
  /** Value format of a field object. */
  format?: ValueFormat;
  /** Value formats of a text object's embedded fields, in the order of embeddedFields. */
  fieldFormats?: ValueFormat[];
  field?: string;
  text?: string;
  embeddedFields?: string[];
  /** A text object's alignment per paragraph (its lines of text, split by "\n"), when stored. */
  paragraphAligns?: ('left' | 'center' | 'right' | 'justify' | undefined)[];
  /** Text object content in order: literal text and embedded fields interleaved. */
  runs?: ({ text: string } | { field: string })[];
  /** Font family. */
  font?: string;
  style?: TextStyle;
  border?: BorderInfo;
  /** Top-left corner in twips (1/1440 inch), relative to the section. */
  position?: { x: number; y: number };
  /** Width and height in twips. */
  size?: { width: number; height: number };
  /** Formatting conditions, e.g. { fontColor: { name: "Font_Color", index: 3 } }. */
  conditions?: Record<string, FormulaRef>;
  /** Picture: number of the "Embedding N" storage holding the image. */
  embedding?: number;
  /** Subreport: number of the "Subdocument N" storage, and whether it runs on demand. */
  subreport?: { index: number; onDemand: boolean };
  crossTab?: CrossTabInfo;
  chart?: ChartInfo;
}

export interface SectionInfo {
  name: string;
  /** Height in twips. */
  height?: number;
  /** Formatting conditions: suppress (Section_Visibility), newPageBefore. */
  conditions?: Record<string, FormulaRef>;
  /** The section's Suppress box is ticked (a suppress formula, when present, decides instead). */
  suppressed?: boolean;
  /** The section's New Page Before box is ticked. */
  newPageBefore?: boolean;
  /** The section format record's flag bytes, as hex (byte 6 is the Suppress box, byte 10 New Page Before). */
  formatFlags?: string;
  objects: ReportObject[];
}

export interface ParameterInfo {
  name: string;
  prompt?: string;
  valueType?: string;
  linkedField?: string;
  /** From the parameter definitions (PromptManager), when present. */
  allowRange?: boolean;
  allowDiscrete?: boolean;
  allowMultiple?: boolean;
  nullable?: boolean;
}

/** Prompt definitions from a PromptManager stream (CRMetaObjects XML). */
export interface PromptInfo {
  group: string;
  prompt: string;
  valueType?: string;
  allowRange: boolean;
  allowDiscrete: boolean;
  allowMultiple: boolean;
  nullable: boolean;
}

/** Reads prompts from CRMetaObjects XML documents with a small tag scanner (no XML library). */
export function parsePrompts(documents: string[]): PromptInfo[] {
  const prompts: PromptInfo[] = [];
  const tag = (xml: string, name: string) => new RegExp(`<${name}>([^<]*)</${name}>`).exec(xml)?.[1];
  const decode = (text: string) => text.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, '&');
  for (const doc of documents) {
    for (const group of doc.split(/<MetaObject\b/).slice(1)) {
      const groupName = decode(tag(group, 'Name') ?? '');
      for (const prompt of group.split(/<Prompt\b/).slice(1)) {
        prompts.push({
          group: groupName,
          prompt: decode(tag(prompt, 'Desc') ?? ''),
          valueType: tag(prompt, 'ValueType'),
          allowRange: tag(prompt, 'AllowRangeValue') === 'true',
          allowDiscrete: tag(prompt, 'AllowDiscreteValue') !== 'false',
          allowMultiple: tag(prompt, 'AllowMultiValues') === 'true',
          nullable: tag(prompt, 'Nullable') === 'true',
        });
      }
    }
  }
  return prompts;
}

/** Adds prompt options to parameters, matched by prompt text or by the prompt group's name. */
export function applyPrompts(parameters: ParameterInfo[], prompts: PromptInfo[]): void {
  for (const parameter of parameters) {
    const prompt = prompts.find((p) => (parameter.prompt && p.prompt === parameter.prompt) || p.group.endsWith(` for ${parameter.name}`) || p.group === parameter.name);
    if (!prompt) continue;
    parameter.allowRange = prompt.allowRange;
    parameter.allowDiscrete = prompt.allowDiscrete;
    parameter.allowMultiple = prompt.allowMultiple;
    parameter.nullable = prompt.nullable;
  }
}

export interface SortInfo {
  field: string;
  descending: boolean;
  /** Sorts groups by a summary value (group sort / Top N) rather than records by a field. */
  bySummary: boolean;
}

export interface GroupOption {
  field: string;
  /** Top N / Bottom N count; 0 when not limited. */
  topN: number;
  /** Whether the remaining groups are kept as an "Others" group. */
  keepOthers: boolean;
  /** Label of the "Others" group. */
  othersName?: string;
}

export interface RunningTotal {
  name: string;
  field: string;
  operation: string;
  /** Field on whose change the total is evaluated, when stored. */
  evaluateOnChangeOf?: string;
}

export interface AreaInfo {
  name: string;
  sections: SectionInfo[];
}

export interface ReportDefinition {
  fileName?: string;
  locale?: string;
  timeZone?: string;
  saveInfo: Record<string, string>;
  formulas: FormulaInfo[];
  /** Text of every formula by its position in the formula list (includes unnamed formatting formulas). */
  formulaTexts?: string[];
  selectionFormulas: SelectionFormulas;
  sqlExpressions: { name: string; text: string }[];
  parameters: ParameterInfo[];
  groups: string[];
  sortFields: string[];
  /** Sort fields with direction. */
  sorts?: SortInfo[];
  /** Per-group options such as Top N. */
  groupOptions?: GroupOption[];
  runningTotals?: RunningTotal[];
  summarizedFields: string[];
  /** Page orientation and paper size, when the report stores printer settings. */
  page?: { orientation: 'portrait' | 'landscape'; paperSize?: number };
  /** Page margins in twips; absent when the report uses the printer's default margins. */
  margins?: { left: number; right: number; top: number; bottom: number };
  layout: AreaInfo[];
}

export interface ConnectionInfo {
  driverLibrary?: string;
  driver?: string;
  database?: string;
  /** Connection properties by name (server, database, provider, user id, ...). */
  properties: Record<string, string>;
}

export interface TableInfo {
  alias: string;
  name: string;
  /** "table" (table or view), "storedProcedure", or "command" (a SQL command written in Crystal). */
  kind: 'table' | 'storedProcedure' | 'command';
  /** Owner / schema, when stored (e.g. "dbo"). */
  schema?: string;
  /** Database (catalog), when the stored name is qualified with it ("Sales.dbo.Orders"). */
  catalog?: string;
  /** SQL text of a command. */
  sql?: string;
  /** Other strings stored on the table record (catalog, qualified name, ...). */
  details?: string[];
  fields: { name: string; type: string; length?: number }[];
}

export interface TableLink {
  from: { table: string; field: string };
  to: { table: string; field: string };
  /**
   * Join type, from the second join code (the query engine's join types, a bit set: 1 inner,
   * 2 left outer, 4 right outer, 8 full outer). "leftOuter" keeps every row of the "from" table.
   */
  join: 'inner' | 'leftOuter' | 'rightOuter' | 'fullOuter' | 'unknown';
  /** Link operator from the first join code (4 = "="). */
  operator: string;
  codes: number[];
}

export interface DataSourceInfo {
  connections: ConnectionInfo[];
  tables: TableInfo[];
  links: TableLink[];
}

const children = (node: RecordNode): RecordNode[] => node.parts.filter((p): p is RecordNode => !(p instanceof Uint8Array));
const ownBytes = (node: RecordNode): Uint8Array =>
  Buffer.concat(node.parts.filter((p): p is Uint8Array => p instanceof Uint8Array));
const ownStrings = (node: RecordNode): string[] => node.parts.flatMap((p: RecordPart) => (p instanceof Uint8Array ? stringsIn(p) : []));

function findAll(nodes: RecordNode[], type: number): RecordNode[] {
  const out: RecordNode[] = [];
  const visit = (n: RecordNode) => {
    if (n.type === type) out.push(n);
    children(n).forEach(visit);
  };
  nodes.forEach(visit);
  return out;
}

const firstChild = (node: RecordNode, type: number) => children(node).find((c) => c.type === type);
const nonEmpty = (values: string[]) => values.filter((v) => v.length > 0);

/** Name and value type held by a nested named-value record. */
function namedValue(node: RecordNode): { name: string; valueType?: string } {
  const nv = firstChild(node, NAMED_VALUE);
  if (!nv) return { name: '' };
  const bytes = ownBytes(nv);
  const name = stringAt(bytes, 0);
  if (!name) return { name: '' };
  const code = bytes[name.length];
  return { name: name.text, valueType: VALUE_TYPES[code] };
}

/** Reads a string or a null string (a zero count with no body). */
function readString(bytes: Uint8Array, pos: number): { text: string; length: number } | undefined {
  if (pos + 4 <= bytes.length && bytes[pos] === 0 && bytes[pos + 1] === 0 && bytes[pos + 2] === 0 && bytes[pos + 3] === 0) {
    return { text: '', length: 4 };
  }
  return stringAt(bytes, pos);
}

/** Formula content: field-reference count (u16), each reference followed by 3 bytes, then the text. */
function parseFormula(node: RecordNode): FormulaInfo {
  const { name, valueType } = namedValue(node);
  const bytes = ownBytes(node);
  const count = (bytes[0] << 8) | bytes[1];
  const referencedFields: string[] = [];
  let pos = 2;
  for (let i = 0; i < count; i++) {
    const ref = readString(bytes, pos);
    if (!ref) return { name, text: longest(ownStrings(node)), referencedFields: [], ...(valueType ? { valueType } : {}) };
    referencedFields.push(ref.text);
    pos += ref.length + 3;
  }
  const text = readString(bytes, pos);
  return { name, text: text ? text.text : longest(ownStrings(node)), referencedFields, ...(valueType ? { valueType } : {}) };
}

/** Formulas Crystal generates for group, cross-tab and summary ordering. */
const INTERNAL_FORMULA = /(#\d+ (Order|Name)$)|^No Summarized Field$/;

/** Crystal names formatting-condition formulas after the property they drive, e.g. Font_Color. */
const CONDITION_NAME = /^[A-Z][a-z]+(_[A-Z][a-z]+)+$/;

/** Records that reference formulas by "@name" as part of the report's own data rather than formatting. */
const DATA_REFERENCE_TYPES = new Set([0x009f, FORMULA, GROUP, SORT_FIELD, SUMMARY, TEXT_EMBEDDED_FIELD, 0x0166, 0x0073, 0x00cb]);

/** Names of formulas referenced ("@name") from formatting records: conditional-format formulas. */
function conditionFormulaNames(records: RecordNode[]): Set<string> {
  const names = new Set<string>();
  const visit = (node: RecordNode) => {
    if (!DATA_REFERENCE_TYPES.has(node.type)) {
      for (const s of ownStrings(node)) if (s.startsWith('@')) names.add(s.slice(1));
    }
    children(node).forEach(visit);
  };
  records.forEach(visit);
  return names;
}

const longest = (values: string[]) => values.reduce((a, b) => (b.length > a.length ? b : a), '');

function position(node: RecordNode): { x: number; y: number } | undefined {
  const bytes = ownBytes(node);
  return bytes.length === 4 ? { x: (bytes[0] << 8) | bytes[1], y: (bytes[2] << 8) | bytes[3] } : undefined;
}

const u16 = (b: Uint8Array, o: number) => (b[o] << 8) | b[o + 1];
const u32 = (b: Uint8Array, o: number) => ((b[o] << 24) | (b[o + 1] << 16) | (b[o + 2] << 8) | b[o + 3]) >>> 0;

/** Colours are stored as 0x00BBGGRR; 0xFFFFFFFF means "none". */
function color(value: number): string | undefined {
  if (value === 0xffffffff) return undefined;
  const hex = (n: number) => n.toString(16).padStart(2, '0');
  return `#${hex(value & 0xff)}${hex((value >> 8) & 0xff)}${hex((value >> 16) & 0xff)}`;
}

/** Object name record: width (u32), height (u32), ..., name. */
function objectSize(nameNode: RecordNode): { width: number; height: number } | undefined {
  const bytes = ownBytes(nameNode);
  if (bytes.length < 8) return undefined;
  const width = u32(bytes, 0);
  const height = u32(bytes, 4);
  return width < 200000 && height < 200000 ? { width, height } : undefined;
}

/** Font: name, family byte, ?, size (u16 pt), ?, italic, ?, underline, ?, ?, weight (u16), height (u32 twips). */
function fontStyle(node: RecordNode): { family: string; style: TextStyle } | undefined {
  const bytes = ownBytes(node);
  const name = stringAt(bytes, 0);
  if (!name) return undefined;
  const b = bytes.subarray(name.length);
  if (b.length < 13) return { family: name.text, style: {} };
  const weight = u16(b, 11);
  return { family: name.text, style: { size: u16(b, 3), bold: weight >= 600, italic: b[6] === 1, underline: b[8] === 1 } };
}

/** Border: side styles (4 bytes), ..., border colour (u32 @10), fill colour (u32 @14), line width (u32 @18). */
function border(node: RecordNode): BorderInfo | undefined {
  const b = ownBytes(node);
  if (b.length < 22) return undefined;
  const info: BorderInfo = { sides: [b[0], b[1], b[2], b[3]] };
  const line = color(u32(b, 10));
  const fill = color(u32(b, 14));
  if (line) info.color = line;
  if (fill) info.background = fill;
  info.width = u32(b, 18);
  return info;
}

/** Formatting-condition slots: (name string, flag byte, formula index u16) repeated; "" / 0xFFFF means unused. */
function conditionSlots(node: RecordNode): (FormulaRef | undefined)[] {
  const b = ownBytes(node);
  const slots: (FormulaRef | undefined)[] = [];
  for (let pos = 0; pos < b.length; ) {
    const name = readString(b, pos);
    if (!name || pos + name.length + 3 > b.length) break;
    pos += name.length;
    const index = u16(b, pos + 1);
    pos += 3;
    slots.push(name.text && index !== 0xffff ? { name: name.text.replace(/^@/, ''), index } : undefined);
  }
  return slots;
}

/**
 * Crystal names a formatting formula after the property it drives (Font_Color, Section_Visibility,
 * New_Page_Before, Tool_Tip_Text, ...). Collects every formula a formatting record refers to,
 * keyed by that property name; a few common ones get short aliases.
 */
const CONDITION_ALIASES: Record<string, string> = {
  font_color: 'fontColor',
  section_visibility: 'suppress',
  suppress: 'suppress',
  new_page_before: 'newPageBefore',
  new_page_after: 'newPageAfter',
  back_color: 'backColor',
  section_back_color: 'backColor',
  background_color: 'backColor',
  object_visibility: 'suppress',
  tool_tip_text: 'toolTip',
  hyperlink_text: 'hyperlink',
};

function namedConditions(node: RecordNode): Record<string, FormulaRef> | undefined {
  const refs = conditionSlots(node).filter((r): r is FormulaRef => r !== undefined);
  if (refs.length === 0) return undefined;
  return Object.fromEntries(refs.map((r) => [CONDITION_ALIASES[r.name.toLowerCase()] ?? r.name, r]));
}

/** Walks the top-level record sequence, where areas, sections and objects follow each other in order. */

/** Strings stored one after another from a position: [strings, position after them]. */
function stringsFrom(bytes: Uint8Array, pos: number, count: number): [string[], number] {
  const out: string[] = [];
  for (let i = 0; i < count; i++) {
    const s = stringAt(bytes, pos);
    if (!s) {
      // An empty string is a length of 1 holding just the terminating zero.
      if (pos + 5 <= bytes.length && u32(bytes, pos) === 1 && bytes[pos + 4] === 0) {
        out.push('');
        pos += 5;
        continue;
      }
      return [out, pos];
    }
    out.push(s.text);
    pos += s.length;
  }
  return [out, pos];
}

/** Number format record: 14 flag bytes, then the thousands separator, decimal separator and currency symbol. */
function numberFormat(node: RecordNode): NumberFormatInfo | undefined {
  const b = ownBytes(node);
  if (b.length < 14) return undefined;
  const [strings] = stringsFrom(b, 14, 3);
  return {
    decimals: b[8], thousands: b[4] === 1, leadingZero: b[6] === 1, negative: b[2],
    symbolType: b[10], symbol: strings[2] ?? '', symbolPosition: b[13],
  };
}

/** Date format record: order, year, month, day, day of week, ..., then the separators. */
function dateFormat(node: RecordNode): DateFormatInfo | undefined {
  const b = ownBytes(node);
  if (b.length < 8) return undefined;
  const [strings] = stringsFrom(b, 8, 5);
  return { order: b[0], year: b[1], month: b[2], day: b[3], dayOfWeek: b[4], separators: [strings[1] ?? '/', strings[2] ?? '/'] };
}

/** Time format record: 12/24-hour, ..., seconds; then the AM and PM strings and the separators. */
function timeFormat(node: RecordNode): TimeFormatInfo | undefined {
  const b = ownBytes(node);
  if (b.length < 5) return undefined;
  const [strings] = stringsFrom(b, 5, 4);
  return { hour12: b[0] === 0, seconds: b[4] !== 2, am: strings[0] ?? 'AM', pm: strings[1] ?? 'PM', hourMinute: strings[2] ?? ':', minuteSecond: strings[3] ?? ':' };
}

/** Reads a value-format record (number, date, time, date-time) into a format. */
function readValueFormat(record: RecordNode, format: ValueFormat): void {
  // The format group starts with a flag: 1 while the field keeps the default format, 0 once it is customised.
  const flag = record.type === 0x00f1 ? firstChild(record, 0x00f0) : undefined;
  if (flag) {
    const b = ownBytes(flag);
    if (b.length >= 4) format.systemDefault = u32(b, 0) === 1;
  }
  const number = firstChild(record, 0x00f8);
  if (number && record.type === 0x00f9) {
    const info = numberFormat(number);
    // The first number format is the one for currency values, the second for other numbers.
    if (info) {
      if (!format.currency) format.currency = info;
      else if (!format.number) format.number = info;
    }
  }
  const date = firstChild(record, 0x00f2);
  if (date && record.type === 0x00f3) format.date = dateFormat(date);
  const time = firstChild(record, 0x00f6);
  if (time && record.type === 0x00f7) format.time = timeFormat(time);
  const order = firstChild(record, 0x00f4);
  if (order && record.type === 0x00f5) {
    const b = ownBytes(order);
    if (b.length) format.dateTimeOrder = b[0];
    const [strings] = stringsFrom(b, 1, 1);
    if (strings[0] !== undefined) format.dateTimeSeparator = strings[0];
  }
}

/**
 * Chart options from the chart's text record (after its style code): the first binary run after the titles
 * holds the legend (byte 1 shown, byte 2 position); a later run starts with the data-label kind and number format.
 */
export function chartOptions(bytes: Uint8Array): Pick<ChartInfo, 'legend' | 'dataLabels'> {
  const runs = tokenize(bytes).filter((t): t is { bytes: Uint8Array } => 'bytes' in t);
  const out: Pick<ChartInfo, 'legend' | 'dataLabels'> = {};
  const options = runs[0]?.bytes;
  if (!options || options.length < 3) return out;
  out.legend = { visible: options[1] === 1, position: options[2] };
  // The data labels: the next run of six or more bytes. Some charts put a 00 00 01 marker and an empty string
  // before it (the marker is then a run of its own); others put the marker and one 00 byte in the same run.
  const run = runs.slice(1).find((r) => r.bytes.length >= 6)?.bytes;
  const at = run && run[0] === 0 && run[1] === 0 && run[2] === 1 ? 4 : 0;
  if (run && run.length >= at + 2 && run[at] <= 3) out.dataLabels = { kind: run[at], format: run[at + 1] };
  return out;
}

const ALIGNMENTS: Record<number, ReportObject['align']> = { 1: 'left', 2: 'center', 3: 'right', 4: 'justify' };

function buildLayout(records: RecordNode[]): AreaInfo[] {
  const areas: AreaInfo[] = [];
  let section: SectionInfo | undefined;
  let object: ReportObject | undefined;
  let crossTab: CrossTabInfo | undefined;
  let areaConditions: Record<string, FormulaRef> | undefined;
  let chartField: string | undefined;

  const currentSection = (): SectionInfo => {
    if (!section) {
      section = { name: '', objects: [] };
      if (areas.length === 0) areas.push({ name: '', sections: [] });
      areas[areas.length - 1].sections.push(section);
    }
    return section;
  };

  const startObject = (node: RecordNode, kind: string) => {
    const nameNode = findAll([node], OBJECT_NAME)[0];
    object = { kind, name: nameNode ? nonEmpty(ownStrings(nameNode))[0] ?? '' : '' };
    const size = nameNode && objectSize(nameNode);
    if (size) object.size = size;
    const fieldNode = findAll([node], 0x009f)[0];
    if (kind === 'field' && fieldNode) object.field = ownStrings(fieldNode)[0];
    if (kind === 'subreport') {
      const b = ownBytes(node);
      if (b.length >= 8) object.subreport = { index: u32(b, 0), onDemand: u16(b, 6) === 1 };
    }
    currentSection().objects.push(object);
  };

  for (const record of records) {
    // Cross-tab block: collect its dimensions and summaries instead of individual objects.
    if (record.type === CROSSTAB_START) {
      startObject(record, 'crossTab');
      crossTab = { rows: [], columns: [], summaries: [] };
      object!.crossTab = crossTab;
      continue;
    }
    if (crossTab) {
      if (record.type === CROSSTAB_END) {
        crossTab = undefined;
        object = undefined;
        continue;
      }
      for (const dimension of findAll([record], CROSSTAB_DIMENSION)) {
        const field = nonEmpty(ownStrings(dimension))[0];
        if (!field) continue;
        const target = findAll([record], CROSSTAB_COLUMN).length ? crossTab.columns : findAll([record], CROSSTAB_ROW).length ? crossTab.rows : undefined;
        if (target && !target.includes(field)) target.push(field);
      }
      // Cell values are summary field objects ("Sum of ..."); row/column headers are "Row #n Name" etc.
      for (const f of findAll([record], 0x009f)) {
        const summary = ownStrings(f)[0];
        if (summary && / of /.test(summary) && !crossTab.summaries.includes(summary)) crossTab.summaries.push(summary);
      }
      if (record.type === OBJECT_POSITION && object && !object.position) object.position = position(record);
      continue;
    }

    if (record.type === AREA) {
      areas.push({ name: nonEmpty(ownStrings(record))[0] ?? '', sections: [] });
      section = object = undefined;
      areaConditions = undefined;
      continue;
    }
    const sectionNode = findAll([record], SECTION)[0];
    if (sectionNode) {
      const bytes = ownBytes(sectionNode);
      section = { name: nonEmpty(ownStrings(sectionNode))[0] ?? '', objects: [] };
      if (bytes.length >= 4) section.height = u32(bytes, 0);
      if (areaConditions) section.conditions = { ...areaConditions };
      if (areas.length === 0) areas.push({ name: '', sections: [] });
      areas[areas.length - 1].sections.push(section);
      object = undefined;
      continue;
    }
    if (record.type === SECTION_CONDITIONS && !object) {
      // The section format (0x00fe): byte 6 is 1 for a visible section and 0 for a suppressed one.
      const format = findAll([record], SECTION_FORMAT)[0];
      const flags = format && ownBytes(format);
      if (section && flags && flags.length > 6 && flags[6] === 0) section.suppressed = true;
      // Byte 10 is 1 when New Page Before is ticked.
      if (section && flags && flags.length > 10 && flags[10] === 1) section.newPageBefore = true;
      if (section && flags) section.formatFlags = Array.from(flags.subarray(0, 24), (b) => b.toString(16).padStart(2, '0')).join('');
      const conditions = namedConditions(record);
      // Before the area's first section the conditions belong to the whole area.
      if (conditions && section) section.conditions = { ...section.conditions, ...conditions };
      else if (conditions) areaConditions = { ...areaConditions, ...conditions };
      continue;
    }
    if (OBJECT_WRAPPERS[record.type]) {
      startObject(record, OBJECT_WRAPPERS[record.type]);
      if (object && (object.kind === 'line' || object.kind === 'box')) {
        // Lines and boxes: the end point is stored; the size comes from the name record.
      }
      if (object?.kind === 'chart') object.chart = { values: [] };
      continue;
    }
    if (OBJECT_KINDS[record.type]) {
      startObject(record, OBJECT_KINDS[record.type]);
      continue;
    }
    const nested = children(record).find((c) => OBJECT_KINDS[c.type]);
    if (nested) {
      startObject(nested, OBJECT_KINDS[nested.type]);
      continue;
    }
    if (!object) continue;
    switch (record.type) {
      case OBJECT_POSITION:
        if (!object.position) object.position = position(record);
        break;
      case TEXT_PARAGRAPH: {
        // A text object's alignment is the paragraph's (byte 12: 1 left, 2 centre, 3 right, 4 justified); the
        // first paragraph's applies to the whole text box.
        const b = ownBytes(record);
        // An alignment set on the object itself is kept when the paragraph just says left.
        if (object.kind === 'text' && !object.runs?.length && b.length > 12 && ALIGNMENTS[b[12]] && (!object.align || b[12] !== 1)) object.align = ALIGNMENTS[b[12]];
        // Each paragraph keeps its own alignment too.
        if (object.kind === 'text') (object.paragraphAligns ??= []).push(b.length > 12 ? ALIGNMENTS[b[12]] : undefined);
        // A new paragraph after existing text is a line break.
        if (object.runs?.length) {
          // The plain text only gets a break after some text; runs keep it for fields too.
          if (object.text) object.text = `${object.text}\n`;
          object.runs.push({ text: '\n' });
        }
        break;
      }
      case TEXT_CONTENT: {
        const text = ownStrings(record).join('');
        object.text = (object.text ?? '') + text;
        if (text) (object.runs ??= []).push({ text });
        break;
      }
      case TEXT_EMBEDDED_FIELD: {
        const field = nonEmpty(ownStrings(record))[0];
        if (field) {
          (object.embeddedFields ??= []).push(field);
          (object.runs ??= []).push({ field });
        }
        break;
      }
      case FONT: {
        const font = fontStyle(record);
        if (font && !object.font) {
          object.font = font.family;
          object.style = { ...font.style, ...(object.style?.color ? { color: object.style.color } : {}) };
        }
        break;
      }
      case FONT_CONDITIONS: {
        const colorNode = firstChild(record, FONT_COLOR);
        const value = colorNode ? ownBytes(colorNode) : undefined;
        if (value && value.length >= 4) {
          const c = color(u32(value, 0));
          if (c && c !== '#000000') object.style = { ...object.style, color: c };
        }
        const conditions = namedConditions(record);
        if (conditions) object.conditions = { ...object.conditions, ...conditions };
        break;
      }
      case 0x00ed: {
        const conditions = namedConditions(record);
        if (conditions) object.conditions = { ...object.conditions, ...conditions };
        const b = firstChild(record, BORDER);
        const info = b && border(b);
        if (info && (info.sides.some((x) => x > 0) || info.background || object.kind === 'line' || object.kind === 'box')) object.border = info;
        break;
      }
      case 0x00fd:
      case 0x00ef:
      case 0x00f1:
      case 0x00f3:
      case 0x00f5:
      case 0x00f7:
      case 0x00f9:
      case 0x00fb: {
        const conditions = namedConditions(record);
        if (conditions) object.conditions = { ...object.conditions, ...conditions };
        if (record.type === 0x00fd && !object.align) {
          // Object format: the third byte is the horizontal alignment.
          const common = firstChild(record, 0x00fc);
          const b = common ? ownBytes(common) : undefined;
          const align = b && b.length > 2 ? ALIGNMENTS[b[2]] : undefined;
          if (align) object.align = align;
          // The second byte is 1 for a visible object and 0 for a suppressed one.
          if (b && b.length > 1 && b[1] === 0) object.suppressed = true;
        }
        if (record.type !== 0x00fd) {
          // Value formats belong to the field object, or to the text object's latest embedded field.
          const embedded = object.embeddedFields?.length ?? 0;
          if (object.kind === 'text' && embedded) {
            const formats = (object.fieldFormats ??= []);
            while (formats.length < embedded) formats.push({});
            readValueFormat(record, formats[embedded - 1]);
          } else if (object.kind === 'field') {
            readValueFormat(record, (object.format ??= {}));
          }
        }
        break;
      }
      case OLE_ITEM: {
        const b = ownBytes(record);
        if (object.kind === 'picture' && b.length >= 4) object.embedding = u32(b, 0);
        break;
      }
      case CHART_VALUES:
        if (object.chart) object.chart.values.push(...nonEmpty(ownStrings(record)));
        break;
      case CHART_ON_CHANGE_OF:
        if (object.chart) object.chart.onChangeOf = nonEmpty(ownStrings(record))[0];
        break;
      case SUMMARY_WRAPPER: {
        // A chart that summarises fields itself ("on change of" a field): each summary is a value it shows.
        const summary = object.chart ? firstChild(record, SUMMARY) : undefined;
        const field = summary ? nonEmpty(ownStrings(summary))[0] : undefined;
        if (object.chart && summary && field) {
          const operation = SUMMARY_OPERATIONS[ownBytes(summary)[0] ?? 0] ?? 'sum';
          const value = `${operation[0].toUpperCase()}${operation.slice(1)} of ${field}`;
          if (!object.chart.values.includes(value)) object.chart.values.push(value);
        }
        break;
      }
      case GROUP: {
        // The chart's "on change of" fields: the first gives the categories, a second one the series.
        const field = object.chart ? nonEmpty(ownStrings(record))[0] : undefined;
        if (object.chart && field) {
          // The bytes after the field: the sixth is the sort order (0 ascending, 1 descending, 2 original order).
          const run = tokenize(ownBytes(record)).find((t): t is { bytes: Uint8Array } => 'bytes' in t && t.bytes.length >= 6);
          const order = run && run.bytes[5] <= 2 ? run.bytes[5] : undefined;
          if (!object.chart.onChangeOf) {
            object.chart.onChangeOf = field;
            if (order !== undefined) object.chart.categoryOrder = order;
          } else if (!object.chart.series && field !== object.chart.onChangeOf) {
            object.chart.series = field;
            if (order !== undefined) object.chart.seriesOrder = order;
          }
        }
        break;
      }
      case CHART_LAYOUT: {
        const b = ownBytes(record);
        // Third byte: the chart's layout (0 advanced: "on change of" fields, 1 group, 2 cross-tab); the last two
        // bytes are an id.
        if (object.chart && b.length >= 3) object.chart.layoutCode = b[2];
        break;
      }
      case CHART_FIELD: {
        // An advanced chart may keep its "on change of" field here instead of in a group record.
        const field = object.chart ? nonEmpty(ownStrings(record)).find((f) => f.includes('.') || f.startsWith('@')) : undefined;
        if (object.chart && field) chartField = field;
        break;
      }
      case CHART_TITLES: {
        if (!object.chart) break;
        const b = ownBytes(record);
        if (!object.chart.onChangeOf && chartField) object.chart.onChangeOf = chartField;
        chartField = undefined;
        Object.assign(object.chart, chartOptions(b.subarray(2)));
        object.chart.styleCode = u16(b, 0);
        if (b.length >= 2) {
          object.chart.family = b[0];
          object.chart.graphType = b[1];
        }
        const strings = stringsIn(b.subarray(2));
        const [title, , , , , categoryTitle, valueTitle] = strings;
        if (title) object.chart.title = title;
        if (categoryTitle) object.chart.categoryTitle = categoryTitle;
        if (valueTitle) object.chart.valueTitle = valueTitle;
        break;
      }
    }
  }
  return areas;
}

export function buildReportDefinition(records: RecordNode[]): ReportDefinition {
  const report: ReportDefinition = {
    saveInfo: {},
    formulas: [],
    selectionFormulas: {},
    sqlExpressions: [],
    parameters: [],
    groups: [],
    sortFields: [],
    summarizedFields: [],
    layout: buildLayout(records),
  };

  const root = records.find((r) => r.type === REPORT_ROOT);
  if (root) {
    for (const s of ownStrings(root)) {
      if (/\.rpt$/i.test(s)) report.fileName = s;
      else if (/^[a-z]{2}(_[A-Z]{2})?$/.test(s)) report.locale = s;
      else if (/Time,/.test(s)) report.timeZone = s;
    }
  }
  for (const node of findAll(records, SAVE_INFO)) {
    const [key, value] = ownStrings(node);
    if (key) report.saveInfo[key] = value ?? '';
  }
  const conditionNames = conditionFormulaNames(records);
  // The formula list: each top-level wrapper holds one formula; formatting conditions refer to it by position.
  report.formulaTexts = [];
  const indexed = new Map<RecordNode, number>();
  records.filter((r) => r.type === FORMULA_WRAPPER).forEach((wrapper, index) => {
    const node = firstChild(wrapper, FORMULA);
    if (node) indexed.set(node, index);
    report.formulaTexts![index] = node ? parseFormula(node).text : '';
  });
  for (const node of findAll(records, FORMULA)) {
    const formula = parseFormula(node);
    const index = indexed.get(node);
    const selection = SELECTION_FORMULAS[formula.name];
    if (selection) {
      if (formula.text) report.selectionFormulas[selection] = formula.text;
    } else if (formula.name) {
      const kind = INTERNAL_FORMULA.test(formula.name) ? 'internal' : conditionNames.has(formula.name) || CONDITION_NAME.test(formula.name) ? 'conditionalFormat' : 'formula';
      report.formulas.push({ name: formula.name, ...(index !== undefined ? { index } : {}), kind, text: formula.text, referencedFields: formula.referencedFields, ...(formula.valueType ? { valueType: formula.valueType } : {}) });
    }
  }
  for (const node of findAll(records, SQL_EXPRESSION)) {
    report.sqlExpressions.push({ name: namedValue(node).name, text: ownStrings(node)[0] ?? '' });
  }
  for (const node of findAll(records, PARAMETER)) {
    const { name, valueType } = namedValue(node);
    const strings = ownStrings(node);
    // The linked field (subreport links) is the second string; the first is the prompt.
    const candidate = strings[1];
    const linkedField = candidate && /^[^{}]+\.[^{}]+$/.test(candidate) && !candidate.startsWith('crobj:') && candidate !== name ? candidate : undefined;
    report.parameters.push({ name, prompt: strings[0] || undefined, valueType, linkedField });
  }
  // Report groups are named "Group #n Name"; cross-tabs and charts have group records of their own.
  const isReportGroup = (node: RecordNode) => ownStrings(node).some((s) => /^Group #\d+ Name$/.test(s));
  for (const node of findAll(records, GROUP).filter(isReportGroup)) {
    const field = ownStrings(node)[0];
    if (field) report.groups.push(field);
  }
  report.sorts = [];
  for (const node of findAll(records, SORT_FIELD)) {
    const bytes = ownBytes(node);
    const field = stringAt(bytes, 0);
    if (!field) continue;
    report.sortFields.push(field.text);
    // After the field: kind (2 = by summary), ?, ?, direction (1 = descending).
    const tail = bytes.subarray(field.length);
    report.sorts.push({ field: field.text, descending: tail[3] === 1, bySummary: tail[0] === 2 });
  }
  report.groupOptions = [];
  for (const node of findAll(records, GROUP).filter(isReportGroup)) {
    const bytes = ownBytes(node);
    const field = readString(bytes, 0);
    if (!field || !field.text) continue;
    // Group: field, 6 bytes, "Others" label, Top N count (u16), keep-others flag (u16).
    const others = readString(bytes, field.length + 6);
    const at = field.length + 6 + (others?.length ?? 0);
    if (!others || at + 4 > bytes.length) continue;
    report.groupOptions.push({ field: field.text, topN: u16(bytes, at), keepOthers: u16(bytes, at + 2) === 1, ...(others.text ? { othersName: others.text } : {}) });
  }
  report.runningTotals = [];
  for (const node of findAll(records, RUNNING_TOTAL)) {
    const summary = firstChild(node, SUMMARY);
    if (!summary) continue;
    const { name } = namedValue(summary);
    const field = nonEmpty(ownStrings(summary))[0];
    const operationCode = ownBytes(summary)[0] ?? 0;
    const evaluate = nonEmpty(ownStrings(node))[0];
    if (name && field) {
      report.runningTotals.push({ name, field, operation: SUMMARY_OPERATIONS[operationCode] ?? `code${operationCode}`, ...(evaluate ? { evaluateOnChangeOf: evaluate } : {}) });
    }
  }
  // Page setup: a flag word, a byte, then left, right, top and bottom margins in twips;
  // 0x80000000 means "use the printer's default margins".
  const pageSetup = findAll(records, PAGE_SETUP)[0];
  if (pageSetup) {
    const b = ownBytes(pageSetup);
    if (b.length >= 19) {
      const [left, right, top, bottom] = [3, 7, 11, 15].map((o) => u32(b, o));
      if (![left, right, top, bottom].some((v) => v >= 0x80000000)) report.margins = { left, right, top, bottom };
    }
  }
  const printer = findAll(records, PRINTER_MODE)[0];
  if (printer) {
    const b = ownBytes(printer);
    if (b.length >= 8) report.page = { orientation: u16(b, 4) === 2 ? 'landscape' : 'portrait', paperSize: u16(b, 6) };
  }
  for (const node of findAll(records, SUMMARY)) {
    const field = nonEmpty(ownStrings(node))[0];
    if (field) report.summarizedFields.push(field);
  }
  return report;
}

/**
 * Some query-engine records nest values in records written without a schema word
 * (flag byte 0xD8: 4-byte length, strings, masked). Collects the strings inside them.
 */
function nestedValueStrings(bytes: Uint8Array): string[] {
  const out: string[] = [];
  const scan = (data: Uint8Array, depth: number) => {
    for (let pos = 0; pos + 6 <= data.length; pos++) {
      if ((data[pos] & 0xfc) !== 0xd8) continue;
      const type = ((data[pos] & 0x03) << 8) | data[pos + 1];
      const length = ((data[pos + 2] << 24) | (data[pos + 3] << 16) | (data[pos + 4] << 8) | data[pos + 5]) >>> 0;
      const end = pos + 6 + length;
      if (length === 0 || end > data.length) continue;
      const content = data.slice(pos + 6, end).map((b) => b ^ (type & 0xff));
      out.push(...stringsIn(content));
      if (depth < 4) scan(content, depth + 1);
      pos = end - 1;
    }
  };
  scan(bytes, 0);
  return out;
}


const SQL_TEXT = /^\s*(select|with|exec(ute)?)\b[\s\S]*$/i;
const STORED_PROCEDURE_NAME = /;\d+$/;

export function buildDataSource(records: RecordNode[]): DataSourceInfo {
  const source: DataSourceInfo = { connections: [], tables: [], links: [] };
  for (const node of findAll(records, QE_CONNECTION)) {
    const [driverLibrary, driver, database] = ownStrings(node);
    const properties: Record<string, string> = {};
    for (const property of children(node).filter((c) => c.type === QE_CONNECTION_PROPERTY)) {
      const [name] = ownStrings(property);
      const value = nestedValueStrings(ownBytes(property)).find((v) => v.length > 0);
      if (name && value !== undefined) properties[name] = value;
    }
    source.connections.push({ driverLibrary, driver, database, properties });
  }

  const fieldsById = new Map<number, { table: string; field: string }>();
  for (const table of findAll(records, QE_TABLE)) {
    const strings = ownStrings(table);
    const [alias = '', , storedName = alias] = strings;
    // Nested records under a table hold index definitions; a SQL command's text may also sit there.
    const candidates = [...strings, ...nestedValueStrings(ownBytes(table))];
    const sql = candidates.find((s) => SQL_TEXT.test(s) && /\b(from|exec)/i.test(s));
    const qualified = storedName.split('.');
    const info: TableInfo = {
      alias,
      name: sql ? alias : qualified[qualified.length - 1],
      kind: sql ? 'command' : STORED_PROCEDURE_NAME.test(storedName) ? 'storedProcedure' : 'table',
      fields: [],
    };
    if (sql) info.sql = sql;
    if (!sql && qualified.length > 1) info.schema = qualified[qualified.length - 2];
    if (!sql && qualified.length > 2 && qualified[qualified.length - 3]) info.catalog = qualified[qualified.length - 3];
    const details = [...new Set(strings.slice(3).filter((s) => s.length > 0 && s !== alias && s !== storedName && s !== sql))];
    if (details.length > 0) info.details = details;
    // The details can list the catalog before the schema ("Sales", "dbo").
    if (!info.catalog && info.schema && details.length > 0) {
      const at = details.indexOf(info.schema);
      if (at > 0) info.catalog = details[at - 1];
    }

    for (const field of children(table).filter((c) => c.type === QE_FIELD)) {
      const bytes = ownBytes(field);
      // Field: 4-byte id, name, a second (usually empty) string, type code (u32), length (u32).
      const fieldName = stringAt(bytes, 4);
      if (!fieldName) continue;
      fieldsById.set(u32(bytes, 0), { table: alias, field: fieldName.text });
      const second = readString(bytes, 4 + fieldName.length);
      const at = 4 + fieldName.length + (second?.length ?? 0);
      if (at + 8 > bytes.length) {
        info.fields.push({ name: fieldName.text, type: 'unknown' });
        continue;
      }
      const code = u32(bytes, at);
      const length = u32(bytes, at + 4);
      info.fields.push({ name: fieldName.text, type: VALUE_TYPES[code] ?? `code${code}`, ...(length !== 0xffffffff ? { length } : {}) });
    }
    source.tables.push(info);
  }

  // Link: 4-byte id, "from" field id, "to" field id, then join codes (4, 1, 1 = inner equal join).
  for (const link of findAll(records, QE_LINK)) {
    const bytes = ownBytes(link);
    if (bytes.length < 12) continue;
    const from = fieldsById.get(u32(bytes, 4));
    const to = fieldsById.get(u32(bytes, 8));
    if (!from || !to) continue;
    const codes: number[] = [];
    for (let o = 12; o + 4 <= bytes.length; o += 4) codes.push(u32(bytes, o));
    const join = ({ 1: 'inner', 2: 'leftOuter', 4: 'rightOuter', 8: 'fullOuter' } as const)[codes[1] as 1 | 2 | 4 | 8] ?? 'unknown';
    const operator = { 4: '=' }[codes[0] as 4] ?? `code${codes[0]}`;
    source.links.push({ from, to, join, operator, codes });
  }
  return source;
}
